import { promisify } from 'util'
import { exec } from 'child_process'
import routeManifest from '#route-manifest.json'
import { StubRouteObject } from '#tests/create-remix-stub.js'

async function runCommand(command: string) {
	const { stdout, stderr } = await promisify(exec)(command)
	if (stderr) throw stderr
	return stdout
}

const json = JSON.parse(await runCommand('npx remix routes --json'))

export const createRouteManifest = ({
	manifest,
}: {
	manifest: typeof routeManifest
}): StubRouteObject[] => {
	return manifest.map(route => {
		return {
			...route,
			file: `!!() => import('#app/${route.file}')!!`,
			children: route.children
				? createRouteManifest({
						manifest: route.children as typeof routeManifest,
				  })
				: undefined,
		}
	}) as StubRouteObject[]
}

process.stdout.write(
	`// This file is autogenerated npm run generate-manifest\nexport const routeManifest = ${JSON.stringify(
		createRouteManifest({ manifest: json }),
		null,
		2,
	)
		.replaceAll('"!!', '')
		.replaceAll('!!"', '')}`,
)
