// This file is autogenerated npm run generate-manifest
export const routeManifest = [
	{
		id: 'root',
		path: '',
		file: () => import('#app/root.tsx'),
		children: [
			{
				id: 'routes/$',
				path: '*',
				file: () => import('#app/routes/$.tsx'),
			},
			{
				id: 'routes/_auth+/auth.$provider',
				path: 'auth/:provider',
				file: () => import('#app/routes/_auth+/auth.$provider.ts'),
				children: [
					{
						id: 'routes/_auth+/auth.$provider.callback',
						path: 'callback',
						file: () => import('#app/routes/_auth+/auth.$provider.callback.ts'),
					},
				],
			},
			{
				id: 'routes/_auth+/forgot-password',
				path: 'forgot-password',
				file: () => import('#app/routes/_auth+/forgot-password.tsx'),
			},
			{
				id: 'routes/_auth+/login',
				path: 'login',
				file: () => import('#app/routes/_auth+/login.tsx'),
			},
			{
				id: 'routes/_auth+/logout',
				path: 'logout',
				file: () => import('#app/routes/_auth+/logout.tsx'),
			},
			{
				id: 'routes/_auth+/onboarding',
				path: 'onboarding',
				file: () => import('#app/routes/_auth+/onboarding.tsx'),
			},
			{
				id: 'routes/_auth+/onboarding_.$provider',
				path: 'onboarding/:provider',
				file: () => import('#app/routes/_auth+/onboarding_.$provider.tsx'),
			},
			{
				id: 'routes/_auth+/reset-password',
				path: 'reset-password',
				file: () => import('#app/routes/_auth+/reset-password.tsx'),
			},
			{
				id: 'routes/_auth+/signup',
				path: 'signup',
				file: () => import('#app/routes/_auth+/signup.tsx'),
			},
			{
				id: 'routes/_auth+/verify',
				path: 'verify',
				file: () => import('#app/routes/_auth+/verify.tsx'),
			},
			{
				id: 'routes/_marketing+/about',
				path: 'about',
				file: () => import('#app/routes/_marketing+/about.tsx'),
			},
			{
				id: 'routes/_marketing+/index',
				index: true,
				file: () => import('#app/routes/_marketing+/index.tsx'),
			},
			{
				id: 'routes/_marketing+/privacy',
				path: 'privacy',
				file: () => import('#app/routes/_marketing+/privacy.tsx'),
			},
			{
				id: 'routes/_marketing+/support',
				path: 'support',
				file: () => import('#app/routes/_marketing+/support.tsx'),
			},
			{
				id: 'routes/_marketing+/tos',
				path: 'tos',
				file: () => import('#app/routes/_marketing+/tos.tsx'),
			},
			{
				id: 'routes/_seo+/robots[.]txt',
				path: 'robots.txt',
				file: () => import('#app/routes/_seo+/robots[.]txt.ts'),
			},
			{
				id: 'routes/_seo+/sitemap[.]xml',
				path: 'sitemap.xml',
				file: () => import('#app/routes/_seo+/sitemap[.]xml.ts'),
			},
			{
				id: 'routes/admin+/cache',
				path: 'admin/cache',
				file: () => import('#app/routes/admin+/cache.tsx'),
			},
			{
				id: 'routes/admin+/cache_.lru.$cacheKey',
				path: 'admin/cache/lru/:cacheKey',
				file: () => import('#app/routes/admin+/cache_.lru.$cacheKey.ts'),
			},
			{
				id: 'routes/admin+/cache_.sqlite',
				path: 'admin/cache/sqlite',
				file: () => import('#app/routes/admin+/cache_.sqlite.tsx'),
				children: [
					{
						id: 'routes/admin+/cache_.sqlite.$cacheKey',
						path: ':cacheKey',
						file: () => import('#app/routes/admin+/cache_.sqlite.$cacheKey.ts'),
					},
				],
			},
			{
				id: 'routes/me',
				path: 'me',
				file: () => import('#app/routes/me.tsx'),
			},
			{
				id: 'routes/resources+/download-user-data',
				path: 'resources/download-user-data',
				file: () => import('#app/routes/resources+/download-user-data.tsx'),
			},
			{
				id: 'routes/resources+/healthcheck',
				path: 'resources/healthcheck',
				file: () => import('#app/routes/resources+/healthcheck.tsx'),
			},
			{
				id: 'routes/resources+/note-images.$imageId',
				path: 'resources/note-images/:imageId',
				file: () => import('#app/routes/resources+/note-images.$imageId.tsx'),
			},
			{
				id: 'routes/resources+/user-images.$imageId',
				path: 'resources/user-images/:imageId',
				file: () => import('#app/routes/resources+/user-images.$imageId.tsx'),
			},
			{
				id: 'routes/settings+/profile',
				path: 'settings/profile',
				file: () => import('#app/routes/settings+/profile.tsx'),
				children: [
					{
						id: 'routes/settings+/profile.change-email',
						path: 'change-email',
						file: () =>
							import('#app/routes/settings+/profile.change-email.tsx'),
					},
					{
						id: 'routes/settings+/profile.connections',
						path: 'connections',
						file: () => import('#app/routes/settings+/profile.connections.tsx'),
					},
					{
						id: 'routes/settings+/profile.index',
						index: true,
						file: () => import('#app/routes/settings+/profile.index.tsx'),
					},
					{
						id: 'routes/settings+/profile.password',
						path: 'password',
						file: () => import('#app/routes/settings+/profile.password.tsx'),
					},
					{
						id: 'routes/settings+/profile.password_.create',
						path: 'password/create',
						file: () =>
							import('#app/routes/settings+/profile.password_.create.tsx'),
					},
					{
						id: 'routes/settings+/profile.photo',
						path: 'photo',
						file: () => import('#app/routes/settings+/profile.photo.tsx'),
					},
					{
						id: 'routes/settings+/profile.two-factor',
						path: 'two-factor',
						file: () => import('#app/routes/settings+/profile.two-factor.tsx'),
						children: [
							{
								id: 'routes/settings+/profile.two-factor.disable',
								path: 'disable',
								file: () =>
									import(
										'#app/routes/settings+/profile.two-factor.disable.tsx'
									),
							},
							{
								id: 'routes/settings+/profile.two-factor.index',
								index: true,
								file: () =>
									import('#app/routes/settings+/profile.two-factor.index.tsx'),
							},
							{
								id: 'routes/settings+/profile.two-factor.verify',
								path: 'verify',
								file: () =>
									import('#app/routes/settings+/profile.two-factor.verify.tsx'),
							},
						],
					},
				],
			},
			{
				id: 'routes/users+/$username',
				path: 'users/:username',
				file: () => import('#app/routes/users+/$username.tsx'),
			},
			{
				id: 'routes/users+/$username_+/notes',
				path: 'users/:username/notes',
				file: () => import('#app/routes/users+/$username_+/notes.tsx'),
				children: [
					{
						id: 'routes/users+/$username_+/notes.$noteId',
						path: ':noteId',
						file: () =>
							import('#app/routes/users+/$username_+/notes.$noteId.tsx'),
					},
					{
						id: 'routes/users+/$username_+/notes.$noteId_.edit',
						path: ':noteId/edit',
						file: () =>
							import('#app/routes/users+/$username_+/notes.$noteId_.edit.tsx'),
					},
					{
						id: 'routes/users+/$username_+/notes.index',
						index: true,
						file: () =>
							import('#app/routes/users+/$username_+/notes.index.tsx'),
					},
					{
						id: 'routes/users+/$username_+/notes.new',
						path: 'new',
						file: () => import('#app/routes/users+/$username_+/notes.new.tsx'),
					},
				],
			},
			{
				id: 'routes/users+/index',
				index: true,
				path: 'users/',
				file: () => import('#app/routes/users+/index.tsx'),
			},
		],
	},
]
